services:
  db:
    image: mysql:8.0
    volumes:
      - ./docker-volumes/db_data:/var/lib/mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    env_file: .env
    depends_on:
      - db
    image: wpdiaries/wordpress-xdebug:latest
    volumes:
      - ./docker-volumes/wordpress:/var/www/html
      - ./docker-volumes/plugins:/var/www/html/wp-content/plugins
      - ./src:/var/www/html/wp-content/plugins/mailbiz-woocommerce-tracker
    ports:
      - "${PORT}:80"
    restart: no
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} mode=debug start_with_request=yes client_port=9003
