name: mailbiz-woocommerce-tracker

networks:
  mailbiz-woocommerce-tracker:
    driver: bridge

services:
  db:
    image: mysql:8.0
    volumes:
      - ./docker-volumes/db_data:/var/lib/mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - mailbiz-woocommerce-tracker

  wordpress:
    env_file: .env
    depends_on:
      - db
    image: wpdiaries/wordpress-xdebug:latest
    volumes:
      - ./docker-volumes/wordpress:/var/www/html
      - ./docker-volumes/plugins:/var/www/html/wp-content/plugins
      # - ./src:/var/www/html/wp-content/plugins/mailbiz-woocommerce-tracker
    ports:
      - "${PORT}:80"
    restart: no
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} mode=debug start_with_request=yes client_port=9003 log_level=${XDEBUG_LOG_LEVEL} log=/tmp/xdebug.log
    networks:
      - mailbiz-woocommerce-tracker

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    env_file: .env
    volumes:
      - ./tests/cases:/usr/app/tests/cases
      - ./src:/usr/app/src 
    restart: no
    tty: true
    environment:
      clear_env: no
      XDEBUG_TRIGGER: trigger
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} mode=debug start_with_request=trigger client_port=9003 log_level=${XDEBUG_LOG_LEVEL} log=/tmp/xdebug.log
